Version 4
SymbolType BLOCK
LINE Normal -32 32 -32 -32
LINE Normal 32 0 -32 32
LINE Normal -32 -32 32 0
LINE Normal 0 -32 0 -16
LINE Normal 0 32 0 16
LINE Normal -20 -16 -28 -16
LINE Normal -19 16 -28 16
LINE Normal -23 11 -23 21
LINE Normal 12 -23 3 -23
LINE Normal 8 -28 8 -18
LINE Normal 12 22 4 22
WINDOW 0 8 -56 Bottom 2
WINDOW 3 8 56 Top 2
SYMATTR Prefix X
SYMATTR Value LM6181/NS-X
SYMATTR ModelFile C:\Users\welcome\AppData\Local\LTspice\lib\sym\AutoGenerated\LM6181_NS-X.txt
PIN -32 16 LEFT 8
PINATTR SpiceOrder 1
PIN -32 -16 LEFT 8
PINATTR SpiceOrder 2
PIN 0 -32 RIGHT 8
PINATTR SpiceOrder 3
PIN 0 32 RIGHT 8
PINATTR SpiceOrder 4
PIN 32 0 RIGHT 8
PINATTR SpiceOrder 5
